package main

import (
	"time"

	"github.com/janekbaraniewski/openusage/internal/core"
)

func buildOpenRouterDemoSnapshot(now time.Time) core.UsageSnapshot {
	return core.UsageSnapshot{
		ProviderID: "openrouter",
		AccountID:  "openrouter",
		Timestamp:  now,
		Status:     core.StatusOK,
		Metrics: map[string]core.Metric{
			"credit_balance": {
				Limit: ptr(10.00), Remaining: ptr(1.72), Used: ptr(8.28), Unit: "USD", Window: "current",
			},
			"usage_daily":    {Used: ptr(0.18), Unit: "USD", Window: "1d"},
			"usage_weekly":   {Used: ptr(6.50), Unit: "USD", Window: "7d"},
			"usage_monthly":  {Used: ptr(8.28), Unit: "USD", Window: "30d"},
			"today_cost":     {Used: ptr(0.18), Unit: "USD", Window: "today"},
			"7d_api_cost":    {Used: ptr(6.50), Unit: "USD", Window: "7d"},
			"30d_api_cost":   {Used: ptr(8.28), Unit: "USD", Window: "30d"},
			"today_requests": {Used: ptr(21), Unit: "requests", Window: "today"},
			"today_input_tokens": {
				Used: ptr(746000), Unit: "tokens", Window: "today",
			},
			"today_output_tokens": {
				Used: ptr(89300), Unit: "tokens", Window: "today",
			},
			"today_reasoning_tokens": {Used: ptr(12200), Unit: "tokens", Window: "today"},
			"today_cached_tokens":    {Used: ptr(181000), Unit: "tokens", Window: "today"},
			"recent_requests":        {Used: ptr(464), Unit: "requests", Window: "recent"},
			"burn_rate":              {Used: ptr(0.04), Unit: "USD/h", Window: "1h"},
			"limit_remaining":        {Used: ptr(1.72), Unit: "USD", Window: "current"},
			"model_qwen_qwen3-coder-flash_cost_usd": {
				Used: ptr(2.44), Unit: "USD", Window: "activity",
			},
			"model_qwen_qwen3-coder-flash_input_tokens": {
				Used: ptr(7800000), Unit: "tokens", Window: "activity",
			},
			"model_qwen_qwen3-coder-flash_output_tokens": {
				Used: ptr(920000), Unit: "tokens", Window: "activity",
			},
			"model_moonshotai_kimi-k2-5_cost_usd": {
				Used: ptr(3.76), Unit: "USD", Window: "activity",
			},
			"model_moonshotai_kimi-k2-5_input_tokens": {
				Used: ptr(5800000), Unit: "tokens", Window: "activity",
			},
			"model_moonshotai_kimi-k2-5_output_tokens": {
				Used: ptr(720000), Unit: "tokens", Window: "activity",
			},
			"model_nvidia_nemotron-nano-9b-v2_cost_usd": {
				Used: ptr(0.02), Unit: "USD", Window: "activity",
			},
			"model_nvidia_nemotron-nano-9b-v2_input_tokens": {
				Used: ptr(381400), Unit: "tokens", Window: "activity",
			},
			"model_nvidia_nemotron-nano-9b-v2_output_tokens": {
				Used: ptr(42000), Unit: "tokens", Window: "activity",
			},
			"model_deepseek_deepseek-v3-2_cost_usd": {
				Used: ptr(0.04), Unit: "USD", Window: "activity",
			},
			"model_deepseek_deepseek-v3-2_input_tokens": {
				Used: ptr(127800), Unit: "tokens", Window: "activity",
			},
			"model_deepseek_deepseek-v3-2_output_tokens": {
				Used: ptr(18500), Unit: "tokens", Window: "activity",
			},
			"model_openai_gpt-o4s-r1203_cost_usd": {
				Used: ptr(0.01), Unit: "USD", Window: "activity",
			},
			"model_openai_gpt-o4s-r1203_input_tokens": {
				Used: ptr(94700), Unit: "tokens", Window: "activity",
			},
			"model_openai_gpt-o4s-r1203_output_tokens": {
				Used: ptr(11200), Unit: "tokens", Window: "activity",
			},
			"provider_alibaba_requests":               {Used: ptr(330), Unit: "requests", Window: "activity"},
			"provider_alibaba_cost_usd":               {Used: ptr(4.79), Unit: "USD", Window: "activity"},
			"provider_alibaba_input_tokens":           {Used: ptr(12400000), Unit: "tokens", Window: "activity"},
			"provider_alibaba_output_tokens":          {Used: ptr(2700000), Unit: "tokens", Window: "activity"},
			"provider_novita_requests":                {Used: ptr(44), Unit: "requests", Window: "activity"},
			"provider_novita_cost_usd":                {Used: ptr(1.98), Unit: "USD", Window: "activity"},
			"provider_novita_input_tokens":            {Used: ptr(3400000), Unit: "tokens", Window: "activity"},
			"provider_novita_output_tokens":           {Used: ptr(840000), Unit: "tokens", Window: "activity"},
			"provider_siliconflow-int4_requests":      {Used: ptr(14), Unit: "requests", Window: "activity"},
			"provider_siliconflow-int4_cost_usd":      {Used: ptr(0.27), Unit: "USD", Window: "activity"},
			"provider_siliconflow-int4_input_tokens":  {Used: ptr(780000), Unit: "tokens", Window: "activity"},
			"provider_siliconflow-int4_output_tokens": {Used: ptr(170300), Unit: "tokens", Window: "activity"},
			"provider_deepinfra_requests":             {Used: ptr(10), Unit: "requests", Window: "activity"},
			"provider_deepinfra_cost_usd":             {Used: ptr(0.24), Unit: "USD", Window: "activity"},
			"provider_deepinfra_input_tokens":         {Used: ptr(420000), Unit: "tokens", Window: "activity"},
			"provider_deepinfra_output_tokens":        {Used: ptr(93600), Unit: "tokens", Window: "activity"},
			"provider_google-vertex_requests":         {Used: ptr(26), Unit: "requests", Window: "activity"},
			"provider_google-vertex_cost_usd":         {Used: ptr(0.41), Unit: "USD", Window: "activity"},
			"provider_google-vertex_input_tokens":     {Used: ptr(1200000), Unit: "tokens", Window: "activity"},
			"provider_google-vertex_output_tokens":    {Used: ptr(280000), Unit: "tokens", Window: "activity"},
			"provider_together_requests":              {Used: ptr(18), Unit: "requests", Window: "activity"},
			"provider_together_cost_usd":              {Used: ptr(0.31), Unit: "USD", Window: "activity"},
			"provider_together_input_tokens":          {Used: ptr(860000), Unit: "tokens", Window: "activity"},
			"provider_together_output_tokens":         {Used: ptr(210000), Unit: "tokens", Window: "activity"},
			"provider_fireworks_requests":             {Used: ptr(22), Unit: "requests", Window: "activity"},
			"provider_fireworks_cost_usd":             {Used: ptr(0.28), Unit: "USD", Window: "activity"},
			"provider_fireworks_input_tokens":         {Used: ptr(740000), Unit: "tokens", Window: "activity"},
			"provider_fireworks_output_tokens":        {Used: ptr(180000), Unit: "tokens", Window: "activity"},
			"upstream_alibaba_requests":               {Used: ptr(330), Unit: "requests", Window: "activity"},
			"upstream_alibaba_cost_usd":               {Used: ptr(4.79), Unit: "USD", Window: "activity"},
			"upstream_alibaba_input_tokens":           {Used: ptr(12400000), Unit: "tokens", Window: "activity"},
			"upstream_alibaba_output_tokens":          {Used: ptr(2700000), Unit: "tokens", Window: "activity"},
			"upstream_novita_requests":                {Used: ptr(44), Unit: "requests", Window: "activity"},
			"upstream_novita_cost_usd":                {Used: ptr(1.98), Unit: "USD", Window: "activity"},
			"upstream_novita_input_tokens":            {Used: ptr(3400000), Unit: "tokens", Window: "activity"},
			"upstream_novita_output_tokens":           {Used: ptr(840000), Unit: "tokens", Window: "activity"},
			"upstream_siliconflow-int4_requests":      {Used: ptr(14), Unit: "requests", Window: "activity"},
			"upstream_siliconflow-int4_cost_usd":      {Used: ptr(0.27), Unit: "USD", Window: "activity"},
			"upstream_siliconflow-int4_input_tokens":  {Used: ptr(780000), Unit: "tokens", Window: "activity"},
			"upstream_siliconflow-int4_output_tokens": {Used: ptr(170300), Unit: "tokens", Window: "activity"},
			"upstream_deepinfra_requests":             {Used: ptr(10), Unit: "requests", Window: "activity"},
			"upstream_deepinfra_cost_usd":             {Used: ptr(0.24), Unit: "USD", Window: "activity"},
			"upstream_deepinfra_input_tokens":         {Used: ptr(420000), Unit: "tokens", Window: "activity"},
			"upstream_deepinfra_output_tokens":        {Used: ptr(93600), Unit: "tokens", Window: "activity"},
			"upstream_google-vertex_requests":         {Used: ptr(26), Unit: "requests", Window: "activity"},
			"upstream_google-vertex_cost_usd":         {Used: ptr(0.41), Unit: "USD", Window: "activity"},
			"upstream_google-vertex_input_tokens":     {Used: ptr(1200000), Unit: "tokens", Window: "activity"},
			"upstream_google-vertex_output_tokens":    {Used: ptr(280000), Unit: "tokens", Window: "activity"},
			"upstream_together_requests":              {Used: ptr(18), Unit: "requests", Window: "activity"},
			"upstream_together_cost_usd":              {Used: ptr(0.31), Unit: "USD", Window: "activity"},
			"upstream_together_input_tokens":          {Used: ptr(860000), Unit: "tokens", Window: "activity"},
			"upstream_together_output_tokens":         {Used: ptr(210000), Unit: "tokens", Window: "activity"},
			"upstream_fireworks_requests":             {Used: ptr(22), Unit: "requests", Window: "activity"},
			"upstream_fireworks_cost_usd":             {Used: ptr(0.28), Unit: "USD", Window: "activity"},
			"upstream_fireworks_input_tokens":         {Used: ptr(740000), Unit: "tokens", Window: "activity"},
			"upstream_fireworks_output_tokens":        {Used: ptr(180000), Unit: "tokens", Window: "activity"},
			"client_pet_tracker_input_tokens":         {Used: ptr(14200000), Unit: "tokens", Window: "30d"},
			"client_pet_tracker_output_tokens":        {Used: ptr(1680000), Unit: "tokens", Window: "30d"},
			"client_pet_tracker_total_tokens":         {Used: ptr(15880000), Unit: "tokens", Window: "30d"},
			"client_pet_tracker_requests":             {Used: ptr(452), Unit: "requests", Window: "30d"},
			"client_pet_tracker_cost_usd":             {Used: ptr(7.84), Unit: "USD", Window: "30d"},
			"client_sandbox_input_tokens":             {Used: ptr(200000), Unit: "tokens", Window: "30d"},
			"client_sandbox_output_tokens":            {Used: ptr(120000), Unit: "tokens", Window: "30d"},
			"client_sandbox_total_tokens":             {Used: ptr(320000), Unit: "tokens", Window: "30d"},
			"client_sandbox_requests":                 {Used: ptr(12), Unit: "requests", Window: "30d"},
			"client_sandbox_cost_usd":                 {Used: ptr(0.44), Unit: "USD", Window: "30d"},
			"client_recipe_blog_input_tokens":         {Used: ptr(5700000), Unit: "tokens", Window: "30d"},
			"client_recipe_blog_output_tokens":        {Used: ptr(680000), Unit: "tokens", Window: "30d"},
			"client_recipe_blog_total_tokens":         {Used: ptr(6380000), Unit: "tokens", Window: "30d"},
			"client_recipe_blog_requests":             {Used: ptr(186), Unit: "requests", Window: "30d"},
			"client_recipe_blog_cost_usd":             {Used: ptr(3.31), Unit: "USD", Window: "30d"},
			"client_expense_tracker_input_tokens":     {Used: ptr(4100000), Unit: "tokens", Window: "30d"},
			"client_expense_tracker_output_tokens":    {Used: ptr(490000), Unit: "tokens", Window: "30d"},
			"client_expense_tracker_total_tokens":     {Used: ptr(4590000), Unit: "tokens", Window: "30d"},
			"client_expense_tracker_requests":         {Used: ptr(135), Unit: "requests", Window: "30d"},
			"client_expense_tracker_cost_usd":         {Used: ptr(2.40), Unit: "USD", Window: "30d"},
			"client_workout_log_input_tokens":         {Used: ptr(2600000), Unit: "tokens", Window: "30d"},
			"client_workout_log_output_tokens":        {Used: ptr(310000), Unit: "tokens", Window: "30d"},
			"client_workout_log_total_tokens":         {Used: ptr(2910000), Unit: "tokens", Window: "30d"},
			"client_workout_log_requests":             {Used: ptr(84), Unit: "requests", Window: "30d"},
			"client_workout_log_cost_usd":             {Used: ptr(1.49), Unit: "USD", Window: "30d"},
			"client_garden_planner_input_tokens":      {Used: ptr(1800000), Unit: "tokens", Window: "30d"},
			"client_garden_planner_output_tokens":     {Used: ptr(200000), Unit: "tokens", Window: "30d"},
			"client_garden_planner_total_tokens":      {Used: ptr(2000000), Unit: "tokens", Window: "30d"},
			"client_garden_planner_requests":          {Used: ptr(59), Unit: "requests", Window: "30d"},
			"client_garden_planner_cost_usd":          {Used: ptr(1.08), Unit: "USD", Window: "30d"},
			// OpenRouter is an API router: it reports spend, tokens, models, and
			// upstream providers, but has no per-tool or per-language telemetry —
			// those come from coding-agent logs (Claude Code, Codex, …). Don't
			// fabricate Tool Usage / Language breakdowns here.
			"analytics_7d_requests": {
				Used: ptr(464), Unit: "requests", Window: "7d",
			},
			"analytics_30d_requests": {
				Used: ptr(464), Unit: "requests", Window: "30d",
			},
			"analytics_7d_tokens": {
				Used: ptr(14.4e6), Unit: "tokens", Window: "7d",
			},
			"analytics_7d_cost": {
				Used: ptr(6.50), Unit: "USD", Window: "7d",
			},
			"analytics_30d_cost": {
				Used: ptr(8.28), Unit: "USD", Window: "30d",
			},
			"analytics_active_days": {Used: ptr(12), Unit: "days", Window: "30d"},
			"analytics_models":      {Used: ptr(24), Unit: "models", Window: "30d"},
			"analytics_providers":   {Used: ptr(4), Unit: "providers", Window: "30d"},
			"keys_total":            {Used: ptr(1), Unit: "keys", Window: "current"},
			"keys_active":           {Used: ptr(1), Unit: "keys", Window: "current"},
		},
		Raw: map[string]string{
			"activity_models":       "24",
			"is_management_key":     "true",
			"key_label":             "demo-key",
			"tier":                  "premium",
			"is_free_tier":          "false",
			"include_byok_in_limit": "false",
			"byok_in_use":           "false",
			"activity_providers":    "alibaba, novita, siliconflow-int4, deepinfra, google-vertex, together, fireworks",
			"model_mix_source":      "generation_live",
			"model_usage":           "qwen qwen3 coder flash: 37%, moonshotai kimi k2 5: 28%, nvidia nemotron nano 9b v2: 18%, deepseek deepseek v3 2: 12%, openai gpt o4s r1203: 5%",
			"model_usage_window":    "30d",
			"client_usage":          "recipe_blog: 40%, expense_tracker: 29%, workout_log: 18%, garden_planner: 13%",
			"generations_fetched":   "464",
		},
		ModelUsage: []core.ModelUsageRecord{
			{
				RawModelID:      "qwen/qwen3-coder-flash",
				Canonical:       "qwen3-coder-flash",
				CanonicalVendor: "qwen",
				CostUSD:         ptr(2.44),
				InputTokens:     ptr(7800000),
				OutputTokens:    ptr(920000),
				Window:          "activity",
				Confidence:      0.95,
			},
			{
				RawModelID:      "moonshotai/kimi-k2-5",
				Canonical:       "kimi-k2-5",
				CanonicalVendor: "moonshotai",
				CostUSD:         ptr(3.76),
				InputTokens:     ptr(5800000),
				OutputTokens:    ptr(720000),
				Window:          "activity",
				Confidence:      0.90,
			},
			{
				RawModelID:      "deepseek/deepseek-v3-2",
				Canonical:       "deepseek-v3-2",
				CanonicalVendor: "deepseek",
				CostUSD:         ptr(0.04),
				InputTokens:     ptr(127800),
				OutputTokens:    ptr(18500),
				Window:          "activity",
				Confidence:      0.95,
			},
		},
		DailySeries: map[string][]core.TimePoint{
			"analytics_cost":                demoPatternSeries(now, 1.72, demoPatternWorkflow...),
			"analytics_requests":            demoPatternSeries(now, 121, demoPatternWorkflow...),
			"cost":                          demoPatternSeries(now, 1.72, demoPatternWorkflow...),
			"requests":                      demoPatternSeries(now, 121, demoPatternWorkflow...),
			"analytics_tokens":              demoPatternSeries(now, 5800000, demoPatternWorkflow...),
			"tokens_client_pet_tracker":     demoPatternSeries(now, 3100000, demoPatternWorkflow...),
			"tokens_client_sandbox":         demoPatternSeries(now, 70000, demoPatternWorkflow...),
			"tokens_client_recipe_blog":     demoPatternSeries(now, 1520000, demoPatternWorkflow...),
			"tokens_client_expense_tracker": demoPatternSeries(now, 1100000, demoPatternWorkflow...),
			"tokens_client_workout_log":     demoPatternSeries(now, 700000, demoPatternWorkflow...),
			"tokens_client_garden_planner":  demoPatternSeries(now, 480000, demoPatternWorkflow...),
			"usage_client_pet_tracker":      demoPatternSeries(now, 80, demoPatternWorkflow...),
			"usage_client_sandbox":          demoPatternSeries(now, 3, demoPatternWorkflow...),
		},
		Message: "$1.72 credits remaining",
	}
}
